release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - windows
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.githash={{.ShortCommit}}

archives:
  -
    id: ssh-agentx
    builds:
    - ssh-agentx
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    files:
      - none*
    replacements:
      386: 32bit
      amd64: 64bit

checksum:
  name_template: 'checksums.txt'
